server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/5619_db #?serverTimezone=UTC
    username: root
    password: Qwertyuiop123
    type: com.alibaba.druid.pool.DruidDataSource
